Frozen autocommit 2024-06-06 18:09:36.616911

diff --git a/ctdb/config/statd-callout b/ctdb/config/statd-callout
--- a/ctdb/config/statd-callout
+++ b/ctdb/config/statd-callout
@@ -1,31 +1,30 @@
 #!/bin/sh
 
-# This must run as root as CTDB tool commands need to access CTDB socket
-[ "$(id -u)" -eq 0 ] || exec sudo "$0" "$@"
-
 # statd must be configured to use this script as its high availability call-out.
 #
-# In most Linux versions this can be done using something like the following...
+# Modern NFS utils versions use /etc/nfs.conf:
+#
+#   [statd]
+#     name = mycluster
+#     ha-callout = /etc/ctdb/statd-callout
+#
+# Older Linux versions may use something like the following...
 #
 # /etc/sysconfig/nfs (Red Hat) or /etc/default/nfs-common (Debian):
-#   NFS_HOSTNAME=myhostname
+#   NFS_HOSTNAME=mycluster
 #   STATD_HOSTNAME="${NFS_HOSTNAME} -H /etc/ctdb/statd-callout"
 #
-# Newer Red Hat Linux variants instead use /etc/nfs.conf:
-#   [statd]
-#     name = myhostname
-#     ha-callout = /etc/ctdb/statd-callout
 
-[ -n "$CTDB_BASE" ] || \
+[ -n "$CTDB_BASE" ] ||
 	CTDB_BASE=$(d=$(dirname "$0") && cd -P "$d" && echo "$PWD")
 
 . "${CTDB_BASE}/functions"
 
 # Overwrite this so we get some logging
-die ()
+die()
 {
-    script_log "statd-callout" "$@"
-    exit 1
+	script_log "statd-callout" "$@"
+	exit 1
 }
 
 # Try different variables to find config file for NFS_HOSTNAME
@@ -41,25 +40,56 @@ if [ -z "$NFS_HOSTNAME" ]; then
 	fi
 fi
 
-[ -n "$NFS_HOSTNAME" ] || \
-    die "NFS_HOSTNAME is not configured. statd-callout failed"
+[ -n "$NFS_HOSTNAME" ] ||
+	die "NFS_HOSTNAME is not configured. statd-callout failed"
 
 ############################################################
 
 ctdb_setup_state_dir "service" "nfs"
 
+find_statd_sm_dir()
+{
+	if [ -n "$CTDB_TEST_MODE" ]; then
+		_f="${CTDB_TEST_TMP_DIR}/sm"
+		mkdir -p "$_f" "${_f}.bak"
+		echo "$_f"
+		return
+	fi
+
+	for _sm_dir in /var/lib/nfs/statd/sm /var/lib/nfs/sm; do
+		if [ -d "$_sm_dir" ]; then
+			echo "$_sm_dir"
+			break
+		fi
+	done
+}
+
+# Ensure the state directory exists and can be written when called as
+# a non-root user.  Assume the user to run as is the owner of the
+# system statd sm directory, since both rpc.statd and sm-notify run as
+# this directory's owner, so it can read and modify the directory.
+create_add_del_client_dir()
+{
+	_dir="$1"
+
+	if [ ! -d "$_dir" ]; then
+		mkdir -p "$_dir" || die "Failed to create directory \"${_dir}\""
+		ref=$(find_statd_sm_dir)
+		[ -n "$ref" ] || die "Failed to find statd sm directory"
+		chown --reference="$ref" "$_dir"
+	fi
+}
+
 # script_state_dir set by ctdb_setup_state_dir()
 # shellcheck disable=SC2154
-d="${script_state_dir}/statd-callout"
+statd_callout_state_dir="${script_state_dir}/statd-callout"
 
-mkdir -p "$d" || die "Failed to create directory \"${d}\""
-cd "$d" || die "Failed to change directory to \"${d}\""
-
-pnn=$(ctdb_get_pnn)
+statd_callout_db="ctdb.tdb"
+statd_callout_queue_dir="${statd_callout_state_dir}/queue"
 
 ############################################################
 
-send_notifies ()
+send_notifies()
 {
 	_smnotify="${CTDB_HELPER_BINDIR}/smnotify"
 
@@ -70,107 +100,110 @@ send_notifies ()
 
 	# Intentionally round to an even number
 	# shellcheck disable=SC2017
-	_state_even=$(( $(date '+%s') / 2 * 2))
+	_state_even=$(($(date '+%s') / 2 * 2))
 
 	_prev=""
-	while read _sip _cip ; do
+	while read -r _sip _cip; do
 		# NOTE: Consider optimising smnotify to read all the
 		# data from stdin and then run it in the background.
 
 		# Reset stateval for each serverip
-		if [ "$_sip" != "$_prev" ] ; then
+		if [ "$_sip" != "$_prev" ]; then
 			_stateval="$_state_even"
 		fi
 
 		# Send notifies for server shutdown
 		"$_smnotify" --client="$_cip" --ip="$_sip" \
-			     --server="$_sip" --stateval="$_stateval"
+			--server="$_sip" --stateval="$_stateval"
 		"$_smnotify" --client="$_cip" --ip="$_sip" \
-			     --server="$NFS_HOSTNAME" --stateval="$_stateval"
+			--server="$NFS_HOSTNAME" --stateval="$_stateval"
 
 		# Send notifies for server startup
 		_stateval=$((_stateval + 1))
 		"$_smnotify" --client="$_cip" --ip="$_sip" \
-			     --server="$_sip" --stateval="$_stateval"
+			--server="$_sip" --stateval="$_stateval"
 		"$_smnotify" --client="$_cip" --ip="$_sip" \
-			     --server="$NFS_HOSTNAME" --stateval="$_stateval"
+			--server="$NFS_HOSTNAME" --stateval="$_stateval"
 	done
 }
 
-delete_records ()
+delete_records()
 {
-	while read _sip _cip ; do
+	while read -r _sip _cip; do
 		_key="statd-state@${_sip}@${_cip}"
 		echo "\"${_key}\" \"\""
-	done | $CTDB ptrans "ctdb.tdb"
+	done | $CTDB ptrans "$statd_callout_db"
+}
+
+############################################################
+
+# Keep a file per server-IP/client-IP pair, to keep track of the last
+# "add-client" or "del-client'.  These get pushed to a database during
+# "update", which will generally be run once each "monitor" cycle.  In
+# this way we avoid scalability problems with flood of persistent
+# transactions after a "notify" when all the clients re-take their
+# locks.
+
+startup()
+{
+	create_add_del_client_dir "$statd_callout_queue_dir"
+
+	$CTDB attach "$statd_callout_db" persistent
 }
 
 ############################################################
 
 case "$1" in
-    # Keep a single file to keep track of the last "add-client" or
-    # "del-client'.  These get pushed to ctdb.tdb during "update",
-    # which will generally be run once each "monitor" cycle.  In this
-    # way we avoid scalability problems with flood of persistent
-    # transactions after a "notify" when all the clients re-take their
-    # locks.
+startup)
+	startup
+	;;
 
-    add-client)
+add-client)
 	# statd does not tell us to which IP the client connected so
 	# we must add it to all the IPs that we serve
 	cip="$2"
 	date=$(date '+%s')
-	# x is intentionally ignored
-	# shellcheck disable=SC2034
-	$CTDB ip -X |
-	tail -n +2 |
-	while IFS="|" read x sip node x ; do
-	    [ "$node" = "$pnn" ] || continue # not us
-	    key="statd-state@${sip}@${cip}"
-	    echo "\"${key}\" \"${date}\"" >"$key"
-	done
+	while read -r sip; do
+		key="statd-state@${sip}@${cip}"
+		file="${statd_callout_queue_dir}/${key}"
+		echo "\"${key}\" \"${date}\"" >"$file"
+	done <"$CTDB_MY_PUBLIC_IPS_CACHE"
 	;;
 
-    del-client)
+del-client)
 	# statd does not tell us from which IP the client disconnected
 	# so we must add it to all the IPs that we serve
 	cip="$2"
-	# x is intentionally ignored
-	# shellcheck disable=SC2034
-	$CTDB ip -X |
-	tail -n +2 |
-	while IFS="|" read x sip node x ; do
-	    [ "$node" = "$pnn" ] || continue # not us
-	    key="statd-state@${sip}@${cip}"
-	    echo "\"${key}\" \"\"" >"$key"
-	done
+	while read -r sip; do
+		key="statd-state@${sip}@${cip}"
+		file="${statd_callout_queue_dir}/${key}"
+		echo "\"${key}\" \"\"" >"$file"
+	done <"$CTDB_MY_PUBLIC_IPS_CACHE"
 	;;
 
-    update)
-        files=$(echo statd-state@*)
-	if [ "$files" = "statd-state@*" ] ; then
-	    # No files!
-	    exit 0
+update)
+	cd "$statd_callout_queue_dir" ||
+		die "Failed to change directory to \"${statd_callout_queue_dir}\""
+	files=$(echo statd-state@*)
+	if [ "$files" = "statd-state@*" ]; then
+		# No files!
+		exit 0
 	fi
-	# Filter out lines for any IP addresses that are not currently
-	# hosted public IP addresses.
-	ctdb_ips=$($CTDB ip | tail -n +2)
-	sed_expr=$(echo "$ctdb_ips" |
-	    awk -v pnn="$pnn" 'pnn == $2 {
-                ip = $1; gsub(/\./, "\\.", ip);
-                printf "/statd-state@%s@/p\n", ip }')
+	sed_expr=$(awk '{
+		ip = $1; gsub(/\./, "\\.", ip);
+		printf "/statd-state@%s@/p\n", ip }' "$CTDB_MY_PUBLIC_IPS_CACHE")
 	# Intentional multi-word expansion for multiple files
 	# shellcheck disable=SC2086
 	items=$(sed -n "$sed_expr" $files)
-	if [ -n "$items" ] ; then
-		if echo "$items"  | $CTDB ptrans "ctdb.tdb" ; then
+	if [ -n "$items" ]; then
+		if echo "$items" | $CTDB ptrans "$statd_callout_db"; then
 			# shellcheck disable=SC2086
 			rm $files
 		fi
 	fi
 	;;
 
-    notify)
+notify)
 	# we must restart the lockmanager (on all nodes) so that we get
 	# a clusterwide grace period (so other clients don't take out
 	# conflicting locks through other nodes before all locks have been
@@ -182,10 +215,10 @@ case "$1" in
 	#echo 0 > /proc/sys/net/ipv4/tcp_max_tw_buckets
 	#echo 0 > /proc/sys/net/ipv4/tcp_max_orphans
 
-	# Delete the notification list for statd, we don't want it to 
+	# Delete the notification list for statd, we don't want it to
 	# ping any clients
-	rm -f /var/lib/nfs/statd/sm/*
-	rm -f /var/lib/nfs/statd/sm.bak/*
+	dir=$(find_statd_sm_dir)
+	rm -f "${dir}/"* "${dir}.bak/"*
 
 	# We must also let some time pass between stopping and
 	# restarting the lock manager.  Otherwise there is a window
@@ -194,7 +227,7 @@ case "$1" in
 	# their locks.
 	nfs_callout_init
 	"$CTDB_NFS_CALLOUT" "stop" "nlockmgr" >/dev/null 2>&1
-        sleep 2
+	sleep 2
 	"$CTDB_NFS_CALLOUT" "start" "nlockmgr" >/dev/null 2>&1
 
 	# we now need to send out additional statd notifications to ensure
@@ -230,13 +263,14 @@ case "$1" in
 	# Construct a sed expression to take catdb output and produce pairs of:
 	#   server-IP client-IP
 	# but only for the server-IPs that are hosted on this node.
-	ctdb_all_ips=$($CTDB ip all | tail -n +2)
-	sed_expr=$(echo "$ctdb_all_ips" |
-	    awk -v pnn="$pnn" 'pnn == $2 {
-                ip = $1; gsub(/\./, "\\.", ip);
-                printf "s/^key.*=.*statd-state@\\(%s\\)@\\([^\"]*\\).*/\\1 \\2/p\n", ip }')
+	sed_expr=$(awk '{
+		       ip = $1; gsub(/\./, "\\.", ip);
+		       printf "s/^key.*=.*statd-state@\\(%s\\)@\\([^\"]*\\).*/\\1 \\2/p\n", ip }' \
+			       "$CTDB_MY_PUBLIC_IPS_CACHE")
 
-	statd_state=$($CTDB catdb ctdb.tdb | sed -n "$sed_expr" | sort)
+	statd_state=$($CTDB catdb "$statd_callout_db" |
+		sed -n "$sed_expr" |
+		sort)
 	[ -n "$statd_state" ] || exit 0
 
 	echo "$statd_state" | send_notifies
@@ -245,10 +279,12 @@ case "$1" in
 	# Remove any stale touch files (i.e. for IPs not currently
 	# hosted on this node and created since the last "update").
 	# There's nothing else we can do with them at this stage.
-	echo "$ctdb_all_ips" |
-	    awk -v pnn="$pnn" 'pnn != $2 { print $1 }' |
-	    while read sip ; do
-		rm -f "statd-state@${sip}@"*
-	    done
+	pnn=$(ctdb_get_pnn)
+	$CTDB ip all |
+		tail -n +2 |
+		awk -v pnn="$pnn" 'pnn != $2 { print $1 }' |
+		while read -r sip; do
+			rm -f "${statd_callout_queue_dir}/statd-state@${sip}@"*
+		done
 	;;
 esac
